### ISSUE TITLE
Unable to get site to load plugins correctly

### ISSUE THREAD

**Issue by jonchay** [ashmaroli/jekyll-data#21]
Hi there, my gem theme consist of a couple of gem dependencies like `jekyll-coffeescript` and `jekyll-archives`. But when I put these in the gem themes' `_config.yml` like so:
```yml
gems:
 - jekyll-coffeescript
 - jekyll-archives
```

It doesn't seem to get the plugins to work, I'll have to get the site to include them in the Gemfile instead:
```
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
  gem 'jekyll-data'
  gem 'jekyll-coffeescript', '~> 1.0.2'
  gem 'jekyll-archives'
end
```

Are there any workarounds? I was hoping by using `jekyll-data` there will be very minimal changes the user has to do to fully onboard my theme. Any advice is appreciated. Thanks!

**Comment by ashmaroli** [comment]
Yes, that is the intention. But there was a bug in the `v0.4.0` release and has been addressed.
Using the `master` branch version of the repo should fix this.
```ruby
group :jekyll_plugins do
  gem 'jekyll-data', git: 'https://github.com/ashmaroli/jekyll-data'
end
```
there are couple of things to note tough:
  - the above will work only if the `gems` array in the user's config file has been commented out. Otherwise, it will override the `gems:` in the theme-gem's config file.
```yaml
# <source>/_config.yml

# Disable the following to let the theme-gem call the required plugins
# gems:
#   - jekyll-feed
```
  - `bundle exec jekyll build / serve` will load the plugins for your theme-gem automatically if your theme-gem lists the plugins as `runtime_dependencies`  (along with this plugin): 
```ruby
# your-theme.gemspec

  s.add_runtime_dependency "jekyll-archives", "~> 2.1"
  s.add_runtime_dependency "jekyll-coffeescript", "~> 1.0"
```
